version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/openjdk:8.0.252
orbs:
  gradle: circleci/gradle@2.1.0
jobs:
  buid_test:
    description: |
      Checkout, build and test a Gradle project.
    executor: my-executor
    steps:
      - checkout
      - run:
          command: >-
            find . -name 'build.gradle.kts' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
          name: Generate Cache Checksum
      - restore_cache:
          key: 'gradle-cache-{{ .Branch }}-{{ checksum "/tmp/gradle_cache_seed" }}'
      - run:
          command: ./gradlew clean build
          name: Build and test
      - store_artifacts:
          path: build/libs
      - save_cache:
          key: 'gradle-cache-{{ .Branch }}-{{ checksum "/tmp/gradle_cache_seed" }}'
          paths:
            - ~/.gradle
      - gradle/collect_test_results
  document:
    description: /
      automatically create api document by dokka
    executor: my-executor
    steps:
      - checkout
      - run:
          command: >-
            find . -name 'build.gradle.kts' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
          name: Generate Cache Checksum
      - restore_cache:
          key: 'gradle-cache-{{ .Branch }}-{{ checksum "/tmp/gradle_cache_seed" }}'
      - run:
          command: ./gradlew dokka
          name: Run dokka
      - store_artifacts:
          path: build/dokka
          prefix: dokka
workflows:
  checkout-build-test-document:
    jobs:
      - buid_test:
          filters:
            branches:
              only: master
      - document:
          requires:
            - buid_test