name: GAC-OIDC SDK test

on:
  push:
    branches:
      - main
    paths:
      - 'sdk/**'
      - '.github/workflows/gac-oidc-sdk-test.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'sdk/**'

  workflow_dispatch:

jobs:
  test-sonarqube:
    name: 'Run tests and scan vulnerabilities by SonarQube'
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: 'jdk'
          java-version: '11'
          check-latest: true

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Scan vulnerabilities
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew build sonarqube --info \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.projectVersion=$GITHUB_SHA
        working-directory: sdk
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
#        with:
#          sudo: true