name: GAC-OIDC SDK test

on:
  push:
    branches:
      - main
    paths:
      - 'sdk/**'
      - '.github/workflows/gac-oidc-sdk-test.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'sdk/**'

  workflow_dispatch:

jobs:
  test-sonarcloud:
    name: 'Run tests and scan vulnerabilities by SonarQube'
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: 'jdk'
          java-version: '11'
          check-latest: true

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew test
        working-directory: sdk

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Scan vulnerabilities by SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.links.homepage=https://github.com/Hackl0us/GAC-OpenID-Connect-temp \
            -Dsonar.java.binaries=build/classes/kotlin \
            -Dsonar.tests=src/test/kotlin \
            -Dsonar.sources=src/main/kotlin \
            -Dsonar.exclusions=**/resources \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
            -Dsonar.junit.reportPaths=sdk/build/test-results/test
        working-directory: sdk

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
#        with:
#          sudo: true