name: GAC sample test

on:
  push:
    branches:
      - main
    paths:
      - 'sample/**'
      - '.github/workflows/sample-test.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'sample/**'

  workflow_dispatch:

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: 'jdk'
          java-version: '11'
          check-latest: true

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('sample/build.gradle.kts', 'sample/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew build
        working-directory: sample

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
#        with:
#          sudo: true